name: Solar System Workflow

on: 
  workflow_dispatch:
  push: 
    branches: 
      - main
      - 'feature/*'
jobs:
  unit-testing:
    name: Unittesting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        