name: Solar System Workflow

on: 
  workflow_dispatch:
  push: 
    branches: 
      - main
      - 'feature/*'
jobs:
  unit-testing:
    name: Unittesting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        
      - name: Setup NodeJS Version
        uses: actions/setup-node@v6
        with:
          node-version: 20
      
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with: 
          path: ~/.npm
          key: ${{ runner.os}}-node-modules-${{ hashFiles('package-lock.jsons')}}

      - name: Install Dependencies
        run: npm install 

       